# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'router_scan_main.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
import target_dialog


class Ui_RouterScanMain(object):
    def setupUi(self, RouterScanMain):
        RouterScanMain.setObjectName("RouterScanMain")
        RouterScanMain.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(RouterScanMain)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 40, 741, 442))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.textBrowser = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.verticalLayout.addWidget(self.textBrowser_2)
        RouterScanMain.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RouterScanMain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        self.menubar.setObjectName("menubar")
        self.menuDevices = QtWidgets.QMenu(self.menubar)
        self.menuDevices.setObjectName("menuDevices")
        self.menuMikroTik = QtWidgets.QMenu(self.menuDevices)
        self.menuMikroTik.setObjectName("menuMikroTik")
        self.menuCVE_2018_14847 = QtWidgets.QMenu(self.menuMikroTik)
        self.menuCVE_2018_14847.setObjectName("menuCVE_2018_14847")
        self.menu_CVE_2018_14847_Action = QtWidgets.QMenu(self.menuCVE_2018_14847)
        self.menu_CVE_2018_14847_Action.setObjectName("menuAction")

        self.menuCVE_2018_14847Exp = QtWidgets.QMenu(self.menuCVE_2018_14847)
        self.menuCVE_2018_14847Exp.setObjectName("Exploit")

        self.menuTP_Link = QtWidgets.QMenu(self.menuDevices)
        self.menuTP_Link.setObjectName("menuTP_Link")
        self.menuDocument = QtWidgets.QMenu(self.menubar)
        self.menuDocument.setObjectName("menuDocument")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        RouterScanMain.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RouterScanMain)
        self.statusbar.setObjectName("statusbar")
        RouterScanMain.setStatusBar(self.statusbar)
        self.actionRouter_1 = QtWidgets.QAction(RouterScanMain)
        self.actionRouter_1.setObjectName("actionRouter_1")
        self.actionRouter_2 = QtWidgets.QAction(RouterScanMain)
        self.actionRouter_2.setObjectName("actionRouter_2")
        self.actionRouter_3 = QtWidgets.QAction(RouterScanMain)
        self.actionRouter_3.setObjectName("actionRouter_3")
        self.actionRouter_4 = QtWidgets.QAction(RouterScanMain)
        self.actionRouter_4.setObjectName("actionRouter_4")
        self.actionCVE_2019_3924 = QtWidgets.QAction(RouterScanMain)
        self.actionCVE_2019_3924.setObjectName("actionCVE_2019_3924")
        self.actionCVE_2019_3943 = QtWidgets.QAction(RouterScanMain)
        self.actionCVE_2019_3943.setObjectName("actionCVE_2019_3943")
        self.actionCVE_1 = QtWidgets.QAction(RouterScanMain)
        self.actionCVE_1.setObjectName("actionCVE_1")
        self.actionCVE_2 = QtWidgets.QAction(RouterScanMain)
        self.actionCVE_2.setObjectName("actionCVE_2")
        self.actionCVE = QtWidgets.QAction(RouterScanMain)
        self.actionCVE.setObjectName("actionCVE")
        self.actionCVE_3 = QtWidgets.QAction(RouterScanMain)
        self.actionCVE_3.setObjectName("actionCVE_3")
        self.actionCVE_4 = QtWidgets.QAction(RouterScanMain)
        self.actionCVE_4.setObjectName("actionCVE_4")
        self.actionSource_Codes = QtWidgets.QAction(RouterScanMain)
        self.actionSource_Codes.setObjectName("actionSource_Codes")
        self.actionAPIs = QtWidgets.QAction(RouterScanMain)
        self.actionAPIs.setObjectName("actionAPIs")
        self.actionUsage = QtWidgets.QAction(RouterScanMain)
        self.actionUsage.setObjectName("actionUsage")
        self.actionContact_Us = QtWidgets.QAction(RouterScanMain)
        self.actionContact_Us.setObjectName("actionContact_Us")
        self.actionUpdate = QtWidgets.QAction(RouterScanMain)
        self.actionUpdate.setObjectName("actionUpdate")

        self.action_CVE_2018_14847_Exploit = QtWidgets.QAction(RouterScanMain)
        self.action_CVE_2018_14847_Exploit.setObjectName("actionExploit")
        self.action_CVE_2018_14847_Exploit.triggered.connect(self.targetUi)

        self.action_CVE_2018_14847_Create_Proxy = QtWidgets.QAction(RouterScanMain)
        self.action_CVE_2018_14847_Create_Proxy.setObjectName("actionCreate_Proxy")
        self.menu_CVE_2018_14847_Action.addAction(self.action_CVE_2018_14847_Create_Proxy)
        self.menu_CVE_2018_14847_Action.addSeparator()
        self.menuCVE_2018_14847.addAction(self.action_CVE_2018_14847_Exploit)
        self.menuCVE_2018_14847.addAction(self.menu_CVE_2018_14847_Action.menuAction())
        self.menuMikroTik.addSeparator()
        self.menuMikroTik.addAction(self.menuCVE_2018_14847.menuAction())
        self.menuMikroTik.addAction(self.actionCVE_2019_3924)
        self.menuMikroTik.addAction(self.actionCVE_2019_3943)
        self.menuMikroTik.addAction(self.actionCVE_1)
        self.menuMikroTik.addAction(self.actionCVE_2)
        self.menuTP_Link.addAction(self.actionCVE)
        self.menuTP_Link.addAction(self.actionCVE_3)
        self.menuTP_Link.addAction(self.actionCVE_4)
        self.menuDevices.addAction(self.menuMikroTik.menuAction())
        self.menuDevices.addAction(self.menuTP_Link.menuAction())
        self.menuDevices.addAction(self.actionRouter_1)
        self.menuDevices.addAction(self.actionRouter_2)
        self.menuDevices.addAction(self.actionRouter_3)
        self.menuDevices.addAction(self.actionRouter_4)
        self.menuDocument.addAction(self.actionSource_Codes)
        self.menuDocument.addAction(self.actionAPIs)
        self.menuDocument.addAction(self.actionUsage)
        self.menuHelp.addAction(self.actionContact_Us)
        self.menuHelp.addAction(self.actionUpdate)
        self.menubar.addAction(self.menuDevices.menuAction())
        self.menubar.addAction(self.menuDocument.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.menuCVE_2018_14847Exp.addAction(self.action_CVE_2018_14847_Exploit)

        self.retranslateUi(RouterScanMain)
        QtCore.QMetaObject.connectSlotsByName(RouterScanMain)

    def retranslateUi(self, RouterScanMain):
        _translate = QtCore.QCoreApplication.translate
        RouterScanMain.setWindowTitle(_translate("RouterScanMain", "Router Scan"))
        self.label.setText(_translate("RouterScanMain", "Input"))
        self.label_2.setText(_translate("RouterScanMain", "Output"))
        self.menuDevices.setTitle(_translate("RouterScanMain", "Devices"))
        self.menuMikroTik.setTitle(_translate("RouterScanMain", "MikroTik"))
        self.menuCVE_2018_14847.setTitle(_translate("RouterScanMain", "CVE-2018-14847"))
        self.menu_CVE_2018_14847_Action.setTitle(_translate("RouterScanMain", "Action"))
        self.menuTP_Link.setTitle(_translate("RouterScanMain", "TP-Link"))
        self.menuDocument.setTitle(_translate("RouterScanMain", "Document"))
        self.menuHelp.setTitle(_translate("RouterScanMain", "Help"))
        self.actionRouter_1.setText(_translate("RouterScanMain", "Router_1"))
        self.actionRouter_2.setText(_translate("RouterScanMain", "Router_2"))
        self.actionRouter_3.setText(_translate("RouterScanMain", "Router_3"))
        self.actionRouter_4.setText(_translate("RouterScanMain", "Router_4"))
        self.actionCVE_2019_3924.setText(_translate("RouterScanMain", "CVE-2019-3924"))
        self.actionCVE_2019_3943.setText(_translate("RouterScanMain", "CVE-2019-3943"))
        self.actionCVE_1.setText(_translate("RouterScanMain", "CVE_1"))
        self.actionCVE_2.setText(_translate("RouterScanMain", "CVE_2"))
        self.actionCVE.setText(_translate("RouterScanMain", "CVE_1"))
        self.actionCVE_3.setText(_translate("RouterScanMain", "CVE_2"))
        self.actionCVE_4.setText(_translate("RouterScanMain", "CVE_3"))
        self.actionSource_Codes.setText(_translate("RouterScanMain", "Source Codes"))
        self.actionAPIs.setText(_translate("RouterScanMain", "APIs"))
        self.actionUsage.setText(_translate("RouterScanMain", "Usage"))
        self.actionContact_Us.setText(_translate("RouterScanMain", "Contact"))
        self.actionUpdate.setText(_translate("RouterScanMain", "Update"))
        self.action_CVE_2018_14847_Exploit.setText(_translate("RouterScanMain", "Exploit"))
        self.action_CVE_2018_14847_Create_Proxy.setText(_translate("RouterScanMain", "Create Proxy"))

    def targetUi(self):
        dialog = QtWidgets.QDialog()
        ui = target_dialog.Ui_target_dialog()
        ui.setupUi(dialog)
        dialog.show()
        dialog.exec_()
